* tvtime/debian/config: Went back to the Perl style installation 	system, so get the ability to go backwards and forwards again. 	Also merged tvtime-configure integration into the configuation 	script, so things are much nicer.  Threw out my XML parser. 	* tvtime/debian/postinst: Ibid.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,101 +1,172 @@
 #! /bin/sh
 # postinst script for tvtime
+#
+# see: dh_installdeb(1)
 
 set -e
 
-action=$1
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+#
+# quoting from the policy:
+#     Any necessary prompting should almost always be confined to the
+#     post-installation script, and should be protected with a conditional
+#     so that unnecessary prompting doesn't happen if a package's
+#     installation fails and the `postinst' is called with `abort-upgrade',
+#     `abort-remove' or `abort-deconfigure'.
 
-CONFIGFILE=/etc/tvtime/tvtime.xml
-
-if [ "$action" = "configure" ]; then
-    # Source debconf library.
-    . /usr/share/debconf/confmodule
-
-    # Handle the setuid bit.
+function setuid () {
     db_get tvtime/setuid
     if [ -x /usr/bin/tvtime -a "$RET" = "false" ] ; then
-        if [ ! -x /usr/sbin/dpkg-statoverride ] || \
-           ! /usr/sbin/dpkg-statoverride --list /usr/bin/tvtime >/dev/null; then
-            chmod u=rwx,go=rx /usr/bin/tvtime
-            chown root:root /usr/bin/tvtime
-        fi
+	if [ ! -x /usr/sbin/dpkg-statoverride ] ||\
+	    ! /usr/sbin/dpkg-statoverride --list /usr/bin/tvtime >/dev/null; then
+	    chmod u=rwx,go=rx /usr/bin/tvtime
+	    chown root:root /usr/bin/tvtime
+	fi
     else
-        if [ ! -x /usr/sbin/dpkg-statoverride ] || \
-           ! /usr/sbin/dpkg-statoverride --list /usr/bin/tvtime >/dev/null; then
-            chmod u=rwxs,go=rx /usr/bin/tvtime
-            chown root:root /usr/bin/tvtime
-        fi
+	if [ ! -x /usr/sbin/dpkg-statoverride ] || \
+	    ! /usr/sbin/dpkg-statoverride --list /usr/bin/tvtime >/dev/null; then
+	    chmod u=rwxs,go=rx /usr/bin/tvtime
+	    chown root:root /usr/bin/tvtime
+	fi
     fi
+}
 
-    # Try to set the /var/run/tvtime directory to video group
-    if [ -d /var/run/tvtime ] ; then
-        if [ ! -x /usr/sbin/dpkg-statoverride ] || \
-           ! /usr/sbin/dpkg-statoverride --list /var/run/tvtime >/dev/null; then
-            chmod ug=rwx,o=rxt /var/run/tvtime
-            chown root:video /var/run/tvtime
-        fi
+# Parse the option requested from tvtime-configure
+function get_option () {
+    OPTION=`tvtime-configure --$1 2>/dev/null | awk -F: '{ print \$2 }'`
+}
+
+function suck_tvtime_xml () {
+    # If tvtime-configure was not there at Debconf, but
+    # /etc/tvtime/tvtime.xml was, then we presume that the
+    # administrator knew what he was doing.  We will therefore suck
+    # this information into the Debconf database now that
+    # tvtime-configure is installed.
+    if [ -f /etc/tvtime/debconf.tvtime.xml ]; then
+	get_option norm
+	db_set tvtime/norm "$OPTION"
+
+	get_option frequencies
+	db_set tvtime/frequencies-ntsc "$OPTION"
+	db_set tvtime/frequencies-jp "$OPTION"
+	db_set tvtime/frequencies-pal "$OPTION"
+
+	get_option device
+	db_set tvtime/v4ldevice "$OPTION"
+
+	get_option vbidevice
+	db_set tvtime/vbidevice "$OPTION"
+
+	get_option priority
+	db_set tvtime/processpriority "$OPTION"
     fi
+}
 
-    db_get tvtime/norm
-    NORM=$RET
-    case "$NORM" in
-        NTSC|PAL-M|PAL-Nc)
-            db_get tvtime/frequencies-ntsc
-            case "$RET" in
-                Cable) FREQTABLE=us-cable ;;
-                Broadcast) FREQTABLE=us-broadcast ;;
-                *) FREQTABLE=us-cable100 ;;
-            esac
-            ;;
-        NTSC-JP)
-            db_get tvtime/frequencies-jp
-            case "$RET" in
-                Cable) FREQTABLE=japan-cable ;;
-                *) FREQTABLE=japan-broadcast ;;
-            esac
-            ;;
-        *)
-            db_get tvtime/frequencies-pal
-            case "$RET" in
-                Europe) FREQTABLE=europe ;;
-                France) FREQTABLE=france ;;
-                Russia) FREQTABLE=russia ;;
-                Australia) FREQTABLE=australia ;;
-                "New Zealand") FREQTABLE=newzealand ;;
-                "China Broadcast") FREQTABLE=china-broadcast ;;
-                "Australia Optus cable") FREQTABLE=australia-optus ;;
-                *) FREQTABLE=custom ;;
-            esac
-            ;;
-    esac
+### MAIN POSTINST ###
+case "$1" in
+    configure)
+	# Load Debconf library
+	. /usr/share/debconf/confmodule
 
-    db_get tvtime/v4ldevice
-    V4LDEV=$RET
-    db_get tvtime/vbidevice
-    VBIDEV=$RET
-    db_get tvtime/processpriority
-    PRI=$RET
+	# Handle the setuid bit.
+	setuid
 
-    # Start with the new default config file.
-    gunzip -c /usr/share/doc/tvtime/examples/default.tvtime.xml.gz > $CONFIGFILE.new
+	# Load /etc/tvtime/tvtime.xml into Debconf, if necessary
+	suck_tvtime_xml
 
-    # Configure tvtime.
-    tvtime-configure --configfile=$CONFIGFILE.new --norm=$NORM \
-	--frequencies=$FREQTABLE --device=$V4LDEV --vbidevice=$VBIDEV \
-	--priority=$PRI
+	# Try to set the /var/run/tvtime directory to video group
+	if [ -d /var/run/tvtime ] ; then
+	    if [ ! -x /usr/sbin/dpkg-statoverride ] || \
+		! /usr/sbin/dpkg-statoverride --list /var/run/tvtime >/dev/null; then
+		chmod ug=rwx,o=rxt /var/run/tvtime
+		chown root:video /var/run/tvtime
+	    fi
+	fi
 
-    # Now run ucf on our new config file.
-    db_stop
+	CONFIGFILE=/etc/tvtime/tvtime.xml
 
-    ucf $CONFIGFILE.new $CONFIGFILE </dev/tty
-    rm -f $CONFIGFILE.new
+	db_get tvtime/norm
+	NORM=$RET
+	case "$NORM" in
+	    NTSC|PAL-M|PAL-Nc)
+		db_get tvtime/frequencies-ntsc
+		case "$RET" in
+		    Cable) FREQTABLE=us-cable ;;
+		    Broadcast) FREQTABLE=us-broadcast ;;
+		    *) FREQTABLE=us-cable100 ;;
+		esac
+		;;
+	    NTSC-JP)
+		db_get tvtime/frequencies-jp
+		case "$RET" in
+		    Cable) FREQTABLE=japan-cable ;;
+		    *) FREQTABLE=japan-broadcast ;;
+		esac
+		;;
+	    PAL|PAL-60|PAL-N|SECAM)
+		db_get tvtime/frequencies-pal
+		case "$RET" in
+		    Europe) FREQTABLE=europe ;;
+		    France) FREQTABLE=france ;;
+		    Russia) FREQTABLE=russia ;;
+		    Australia) FREQTABLE=australia ;;
+		    "New Zealand") FREQTABLE=newzealand ;;
+		    "China Broadcast") FREQTABLE=china-broadcast ;;
+		    "Australia Optus cable") FREQTABLE=australia-optus ;;
+		    *) FREQTABLE=custom ;;
+		esac
+		;;
+	    *)
+		FREQTABLE=custom
+		;;
+	esac
 
-    # Create the video devices if they don't exist.
-    if [ ! -c '/dev/video0' ]; then
-        echo "Creating video devices in \`/dev'."
-        ( cd /dev; ./MAKEDEV video )
-    fi
-fi
+	db_get tvtime/v4ldevice
+	V4LDEV=$RET
+	db_get tvtime/vbidevice
+	VBIDEV=$RET
+	db_get tvtime/processpriority
+	PRI=$RET
+
+	db_stop
+
+	# Create the configuration file if it doesn't exist
+	if [ ! -f $CONFIGFILE ]; then
+	    gunzip -c /usr/share/doc/tvtime/examples/default.tvtime.xml.gz \
+		> $CONFIGFILE
+	fi
+
+	# Configure tvtime.
+	tvtime-configure --configfile="$CONFIGFILE" --norm="$NORM" \
+	    --frequencies="$FREQTABLE" --device="$V4LDEV" \
+	    --vbidevice="$VBIDEV" --priority="$PRI" 2>/dev/null
+
+	# Create the video devices if they don't exist.
+	if [ ! -c '/dev/video0' ]; then
+	    echo "Creating video devices in \`/dev'."
+	    ( cd /dev; ./MAKEDEV video )
+	fi
+	;;
+    abort-upgrade|abort-remove|abort-deconfigure)
+
+	;;
+    *)
+	echo "postinst called with unknown argument \`$1'" >&2
+	exit 1
+	;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
